str="India Is My Country."
print(str)
print(str.capitalize())# only 1st char capital
#print("CaseFold:",str.casefold())# all str are small
#print("Center:",str.center(50))
#print("Count:",str.count('I'))
#print("Endwith: ",str.endswith("y"))
#print(str.find("is"))
#print(str.format(2,5))
#print(str.index("ia"))
#print(" ".isalnum())
#print("1".isalpha())
#print("a".isdecimal())
#print("1".isdigit())
#print("1.1".isnumeric())
#print("int".isidentifier())
#print("Abs".islower())
#print("Abc".istitle())
#print("a".isupper())
#print("-".join("Tops"))
#print(str.ljust(30,'*'))
#print(str.lower())
#print(str.upper())
#print(str.partition(' I'))
#print(str.replace("d","D"))
#print(str.split("o",maxsplit=3))
#print(str.swapcase())
#print(str.title())
