# Generated by Django 5.1.5 on 2025-01-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_signup_usersignup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='lastname',
        ),
    ]
