# Generated by Django 5.1.5 on 2025-02-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_doctor_patient_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='exit', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='exit', max_length=254),
            preserve_default=False,
        ),
    ]
