# Generated by Django 5.1.5 on 2025-02-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_doctor_contact_alter_patient_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
