# Generated by Django 5.1.5 on 2025-02-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('contact', models.BigIntegerField()),
                ('dt', models.DateTimeField()),
            ],
        ),
    ]
