# Generated by Django 5.1.5 on 2025-02-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_appoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='doctimg')),
                ('name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('address', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
