# Generated by Django 5.1.4 on 2024-12-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emd_id',
            new_name='emp_id',
        ),
    ]
