# Generated by Django 4.1 on 2024-12-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='usersignup',
        ),
    ]
