# Generated by Django 5.1.6 on 2025-02-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Bungalow', 'Bungalow'), ('RowHouse', 'Rowhouse')], max_length=20)),
                ('listing_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], max_length=10)),
                ('price', models.BigIntegerField()),
                ('address', models.TextField()),
                ('area', models.PositiveIntegerField(help_text='Size in square feet')),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('floors', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='file')),
            ],
        ),
        migrations.CreateModel(
            name='usersignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=20)),
                ('cpwd', models.CharField(max_length=20)),
                ('contact', models.BigIntegerField()),
            ],
        ),
    ]
