# Generated by Django 5.1.6 on 2025-02-24 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='file',
        ),
        migrations.AddField(
            model_name='house',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(default='timezone.now', upload_to='house_images/'),
            preserve_default=False,
        ),
    ]
