# Generated by Django 5.1.6 on 2025-02-24 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_remove_house_file_house_created_house_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image',
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_images/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='society.house')),
            ],
        ),
    ]
