# Generated by Django 5.1.6 on 2025-03-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0006_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='main_image',
            field=models.ImageField(default=1, upload_to='house_images/'),
            preserve_default=False,
        ),
    ]
