# Generated by Django 5.1.6 on 2025-03-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addhome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('size', models.FloatField()),
                ('bedroom', models.IntegerField()),
                ('desc', models.TextField()),
                ('htype', models.CharField(max_length=10)),
                ('price', models.BigIntegerField()),
                ('img', models.ImageField(upload_to='house_imgs/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
