# Generated by Django 5.1.6 on 2025-03-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_addhome'),
    ]

    operations = [
        migrations.AddField(
            model_name='addhome',
            name='rprice',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
