# Generated by Django 5.1.6 on 2025-03-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_addhome_rprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addhome',
            name='rprice',
        ),
    ]
