# Generated by Django 5.1.6 on 2025-03-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_addhome_rprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='addhome',
            name='rprice',
            field=models.BigIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
