# Generated by Django 5.1.6 on 2025-03-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_addhome_price_alter_addhome_rprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addhome',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addhome',
            name='rprice',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
