# Generated by Django 5.1.6 on 2025-03-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_addhome_price_alter_addhome_rprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addhome',
            name='htype',
            field=models.CharField(choices=[('rent', 'Rent'), ('sell', 'Sell')], max_length=10),
        ),
    ]
