# Generated by Django 5.1.6 on 2025-03-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_addhome_htype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addhome',
            name='htype',
            field=models.CharField(choices=[('rent', 'rent'), ('sell', 'sell')], max_length=10),
        ),
    ]
