# Generated by Django 5.1.6 on 2025-03-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_addhome_htype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addhome',
            name='img',
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_imgs/')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.addhome')),
            ],
        ),
    ]
