# Generated by Django 5.1.6 on 2025-03-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='reset_pwd',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
