# Generated by Django 5.1.6 on 2025-03-28 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reqtour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addhome',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.owner'),
        ),
    ]
