# Generated by Django 5.1.6 on 2025-03-31 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_addhome_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addhome',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addhome_set', to='myapp.owner'),
        ),
    ]
