# Generated by Django 5.1.4 on 2024-12-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Christmasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santa',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
